# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenAPIClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenAPIClient
  pod "Alamofire"
  pod "SwiftyJSON"
  pod 'AnyCodable-FlightSchool', '~> 0.6.0'
end

target 'Samples' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Samples

end
